"""Init

Revision ID: a651b1de9b92
Revises:
Create Date: 2026-07-06 18:21:11.164099

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a651b1de9b92"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_cache",
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("discord_message_id", sa.String(), nullable=False),
        sa.Column("telegram_message_id", sa.String(), nullable=True),
        sa.Column("source_channel_id", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("original_headline", sa.Text(), nullable=False),
        sa.Column("normalized_headline", sa.Text(), nullable=False),
        sa.Column("translated_headline", sa.Text(), nullable=True),
        sa.Column("summary_ar", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("market_bias", sa.String(), nullable=True),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("affected_assets", sa.JSON(), nullable=True),
        sa.Column("actual", sa.String(), nullable=True),
        sa.Column("forecast", sa.String(), nullable=True),
        sa.Column("previous", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "NORMALIZED",
                "DEDUPLICATED",
                "STORED",
                "AI_PENDING",
                "AI_SUCCESS",
                "AI_FAILED",
                "TELEGRAM_PENDING",
                "PUBLISHED",
                "UPDATED",
                "FAILED",
                name="newsstatus",
            ),
            nullable=False,
        ),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_hash"), "news", ["hash"], unique=False)
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("news_id", sa.String(), nullable=False),
        sa.Column("step", sa.String(), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_logs_news_id"), "processing_logs", ["news_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_logs_news_id"), table_name="processing_logs")
    op.drop_table("processing_logs")
    op.drop_index(op.f("ix_news_hash"), table_name="news")
    op.drop_table("news")
    op.drop_table("ai_cache")
    # ### end Alembic commands ###
